"use client";

import { jsPDF } from "jspdf";

type Props = {
  total: number;
};

export default function DownloadReport({ total }: Props) {
  const generatePDF = () => {
    const doc = new jsPDF();

    let score = "Carbon Heavy 🔴";

    if (total < 200) {
      score = "Green Hero 🟢";
    } else if (total < 400) {
      score = "Eco Explorer 🟡";
    }

    doc.setFontSize(22);
    doc.text("EcoTrack AI Sustainability Report", 20, 20);

    doc.setFontSize(14);
    doc.text(
      `Total Carbon Footprint: ${total.toFixed(2)} kg CO₂`,
      20,
      40
    );

    doc.text(`Carbon Score: ${score}`, 20, 55);

    doc.text(
      "Thank you for tracking your environmental impact.",
      20,
      75
    );

    doc.text(
      "Generated by EcoTrack AI",
      20,
      95
    );

    doc.save("EcoTrack_Report.pdf");
  };

  return (
    <button
      aria-label="Download Sustainability Report"
      onClick={generatePDF}
      className="mt-6 bg-blue-600 text-white px-5 py-3 rounded-lg hover:bg-blue-700"
    >
      📄 Download Sustainability Report
    </button>
  );
}