"use client";

import { jsPDF } from "jspdf";

type Props = {
  total: number;
};

export default function DownloadReport({ total }: Props) {
  const generatePDF = () => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("EcoTrack AI Sustainability Report", 20, 20);

    doc.setFontSize(14);
    doc.text(`Total Carbon Footprint: ${total.toFixed(2)} kg CO₂`, 20, 40);

    let score = "Carbon Heavy";

    if (total < 200) {
      score = "Green Hero";
    } else if (total < 400) {
      score = "Eco Explorer";
    }

    doc.text(`Carbon Score: ${score}`, 20, 55);

    doc.text(
      "Generated by EcoTrack AI",
      20,
      80
    );

    doc.save("EcoTrack_Report.pdf");
  };

  return (
    <button
      onClick={generatePDF}
      className="mt-6 bg-blue-600 text-white px-5 py-3 rounded-lg hover:bg-blue-700"
    >
      📄 Download Sustainability Report
    </button>
  );
}